services:
  # 1. 网易云音乐 API 服务
  netease-api:
    image: moefurina/ncm-api:latest
    container_name: music-party-netease
    restart: always
    environment:
      - PORT=3000
      - HTTPS=true
    networks:
      - music-net

  # 2. Music Party 主应用
  music-party:
    image: thornex/music-party:latest
    container_name: music-party-app
    restart: always
    ports:
      - "8848:8080" 
    environment:
      # 管理员密码，用于在搜索框输入指令控制系统
      - ADMIN_PASSWORD=admin123
      
      # 网易云 API 地址，指向上面的容器名
      - NETEASE_API_URL=http://netease-api:3000
      
      # [基础配置]
      - BASE_URL=http://localhost:8848    #你的基础url，用于直播流链接的拼接
      - APP_AUTHOR_NAME=晓猫窝      # 页面左上角显示的作者名
      - APP_BACK_WORDS=MUSIC PARTY    # 中间背景装饰文字

    depends_on:
      - netease-api
    networks:
      - music-net
    volumes:
      # 挂载音频缓存目录，防止重启后 B 站歌曲重新下载
      - ./music_party/cached_media:/app/cached_media
      # 挂载数据目录，用于持久化播放列表和历史记录
      - ./music_party/data:/app/data

networks:
  music-net:
    driver: bridge
